/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Safelist grid column classes for dynamic sections
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-6',
    'grid-cols-8',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'md:grid-cols-6',
    'md:grid-cols-8',
    'lg:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'lg:grid-cols-6',
    'lg:grid-cols-8',
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#fff7fb",
        "surface": "#1a0425",
        "inverse-primary": "#8523dd",
        "on-tertiary-fixed": "#291200",
        "secondary-fixed": "#f0c1ff",
        "primary": "#ca98ff",
        "on-tertiary-container": "#442100",
        "on-primary-container": "#350062",
        "on-background": "#f9dcff",
        "error": "#ff6e84",
        "tertiary": "#ff9f4a",
        "purple": {
          50: "#fbf7fd",
          100: "#f5eefa",
          200: "#e8d9f3",
          300: "#d5bce7",
          400: "#b890d5",
          500: "#9a6abd",
          600: "#7a3e8e", // Brand Purple
          700: "#653376",
          800: "#542c62",
          900: "#462751",
          950: "#2c1435",
        },
        "primary-fixed-dim": "#b772ff",
        "background": "#1a0425",
        "secondary-dim": "#d18aee",
        "primary-fixed": "#c185ff",
        "on-tertiary-fixed-variant": "#5a2e00",
        "outline-variant": "#593e63",
        "primary-dim": "#9c42f4",
        "secondary-fixed-dim": "#e9aeff",
        "surface-container-low": "#21072d",
        "on-primary-fixed-variant": "#420078",
        "outline": "#896b93",
        "secondary-container": "#692886",
        "surface-container": "#290c36",
        "on-error-container": "#ffb2b9",
        "surface-dim": "#1a0425",
        "on-secondary-fixed-variant": "#743391",
        "tertiary-fixed-dim": "#f58600",
        "tertiary-dim": "#ed8200",
        "tertiary-container": "#fd8b00",
        "on-secondary": "#520c70",
        "on-primary-fixed": "#000000",
        "primary-container": "#c185ff",
        "on-surface": "#f9dcff",
        "surface-variant": "#391648",
        "secondary": "#e097fd",
        "surface-container-lowest": "#000000",
        "on-primary": "#46007d",
        "on-surface-variant": "#c1a0cb",
        "on-tertiary": "#532a00",
        "tertiary-fixed": "#ff9734",
        "on-error": "#490013",
        "surface-container-highest": "#391648",
        "on-secondary-fixed": "#540f72",
        "surface-container-high": "#31113f",
        "surface-bright": "#411c51",
        "error-container": "#a70138",
        "inverse-on-surface": "#674b71",
        "error-dim": "#d73357",
        "surface-tint": "#ca98ff",
        "on-secondary-container": "#efc0ff",
        cream: '#FFF3E0',
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}

